export default ACTION_TYPES = {
    FETCH_IN_PROGRESS: "FETCH_IN_PROGRESS",
    FETCH_FAILURE: "FETCH_FAILURE",
    FETCH_SUCCESS: "FETCH_SUCCESS",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
    ERROR: "ERROR",
}
